# Generated by Django 5.0.6 on 2024-06-15 18:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('patente', models.CharField(max_length=10, unique=True, verbose_name='Patente')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('imagen', models.CharField(verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cuit', models.PositiveIntegerField(unique=True, verbose_name='CUIT')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('username', models.CharField(max_length=100, verbose_name='Nombre de Usuario')),
                ('password', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.datetime(2024, 6, 15, 18, 55, 8, 900889, tzinfo=datetime.timezone.utc), verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(default=datetime.datetime(2024, 6, 15, 18, 55, 8, 900889, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin')),
                ('precio_total', models.FloatField(blank=True, verbose_name='Precio total')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentacars.auto', verbose_name='Auto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentacars.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
