# Generated by Django 5.0.6 on 2024-06-05 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('precio_total', models.IntegerField(verbose_name='Precio total')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentacars.auto', verbose_name='Auto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentacars.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
