# Generated by Django 5.0.6 on 2024-06-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacars', '0002_alquiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='', max_length=100, verbose_name='Contraseña'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre de Usuario'),
            preserve_default=False,
        ),
    ]
